#\!/bin/bash

echo "=== WhatsApp Integration Setup ==="
echo ""
echo "Step 1: Start ngrok"
echo "Run this command in a new terminal:"
echo ""
echo "  ngrok http 3000"
echo ""
echo "Step 2: Copy the ngrok URL (e.g., https://xxxx.ngrok.io)"
echo ""
echo "Step 3: Configure WhatsApp Webhook in Meta Developer Console:"
echo "  1. Go to https://developers.facebook.com/apps/${WHATSAPP_BUSINESS_ACCOUNT_ID}/whatsapp-business/wa-dev-console"
echo "  2. Go to Configuration → Webhooks"
echo "  3. Click 'Edit' and enter:"
echo "     - Callback URL: https://YOUR-NGROK-URL.ngrok.io/webhook"
echo "     - Verify Token: education_bot_verify_2024"
echo "  4. Subscribe to these webhook fields:"
echo "     - messages"
echo "     - message_status"
echo "     - message_template_status_update"
echo ""
echo "Step 4: Test by sending a message to your WhatsApp number"
echo ""
echo "Your WhatsApp Configuration:"
echo "  Phone Number ID: 780151865181414"
echo "  Business Account ID: 2547033899011381"
echo "  Verify Token: education_bot_verify_2024"
echo ""
